commands.py, listeners.py, plugin.py, pyproject.toml, ui.py, utils.py
The original idea of this PR was to slightly improve Copilot's suggestion and remove the part of the suggestion that is already present in the line. But when I started working on it I realised that it would require some refactoring as the package wasn't designed to handle suggestions in that way. So I ended up with this PR. 
Here is a short summary of what this PR does:
- parses suggestions and removes the part of the text that it is already visible(this is only the case for completion inside line). This provides a much better user experience because in most cases you can use the suggestion as it is as previously you had to correct all accepted suggestions from the middle of the line 
- keeps the current suggestion in the view settings that allows having a custom context and binding …
=> Refactor Copilot suggestions to provide better completion experience

commands.py, listeners.py, ui.py
I think it would be nice to hide the suggestion when switching between views.
This PR also removes underscore for the `Accept ⇥` link. I think it is a bit cleaner this way
Accept
=> feat: hide suggestion on focus lost

Default.sublime-keymap, commands.py, listeners.py, plugin.py, sublime-package.json, types.py, ui.py, utils.py
https://user-images.githubusercontent.com/6594915/179384384-a0e35df5-7184-4369-972b-2195edd755ee.mp4
Use `alt+[` and `alt+]` to do completion cycling.
---
Now we store following things in view settings:
- is_visible
- is_waiting
- completions (full completions payload from copilot)
- completion_index (0-based index of the current chosen completion)
---
Resolves #6
=> feat: previous/next completions

LSP-copilot.sublime-settings, commands.py, listeners.py, sublime-package.json
When I started working on this PR my idea was to only add `hook_to_auto_complete_command` settings so the copilot completion appears after clicking `ctrl+space`.  
But then I realised that our current approach of handling the `modified` event breaks the undo functionality(it undos symbol by symbols instead of changes) so this PR also fixes that
=> feat: hook to auto_complete command

plugin/ui/completion.py, plugin/ui/panel_completion.py, plugin/utils.py
Fixes https://github.com/TheSecEng/LSP-copilot/issues/30
=> fix: PHP syntax highlighting in completions

plugin/ui/completion.py, plugin/ui/panel_completion.py, plugin/utils.py
Fixes https://github.com/TheSecEng/LSP-copilot/issues/33
---
For example, syntax highlighting for completing JS codes inside Markdown fenced code block.
The main idea is to get the deepest/last `source | text | embedding` scope and find the languageId for it.
For the example above, the scope at the cursor is `text.html.markdown markup.raw.code-fence.javascript.markdown-gfm source.js`. We should take `source.js` for resolving languageId rather than `text.html.markdown`.
=> fix: wrong syntax highlighting for embedded languages

plugin/commands.py, plugin/ui/panel_completion.py
Say your cursor is near the bottom of the viewport. After accepting a multiline completion, the completed text can be out of the viewport. This PR mimics what will happen as-if you paste those completion codes at the cursor position. ST will scroll the viewport.
- `animation_enabled` is a default ST settings. (Controls animation throughout the application)
=> fix: scroll view to make full completed text visible

plugin/commands.py, plugin/listeners.py, plugin/ui/completion.py, plugin/utils.py
Since those settings must exist, there is no need to add default values.
If they break, that means there are issues like typo in our codes.
Also renames `get_settings` to `get_session_settings`.
=> refactor: remove default when getting existing settings

plugin/commands.py, plugin/constants.py, plugin/listeners.py, plugin/plugin.py, plugin/utils.py
This PR does following things.
- Real debounce implementation.  I.e., only the last call will be executed during a time frame.
- Do not show popup for `REQ_GET_COMPLETIONS` results but only show popup for `REQ_GET_COMPLETIONS_CYCLING` results.
- Remove `CopilotAskCompletionsCyclingCommand` since it makes no sense to use it alone.
=> refactor: better completion debounce implementation

plugin/commands.py, plugin/ui/completion.py
Besides, I don't like the following. `ViewCompletionManager` shouldn't be coupled with `phantom`-related thing.
```py
class ViewCompletionManager:
@property
def is_phantom(self) -> bool:
return self.completion_style == _PhantomCompletion.STYLE_TYPE
def handle_selection_change(self) -> None:
if not (self.is_phantom and self.is_visible):
return
self.hide()
def handle_text_change(self) -> None:
if not (self.is_phantom and self.is_visible):
return
self.hide()
def handle_close(self) -> None:
if not self.is_phantom:
return
self.completion_style_type.close(self.view)
```
=> tentative refactoring for #27

plugin/listeners.py, plugin/ui/completion.py
Some LSP servers are slower than others, and, for example, formatting on save (that is caused by the `lsp_save` command) can take a bit longer.  
Because of that, the `on_modified_async` callback gets triggered in the middle of the call and a completion gets displayed(because it may have formatted the source code).
This PR blocks the completion request during the `lsp_save` command duration
=> fix: do not get completions during the lsp_save command

Default.sublime-keymap, plugin/listeners.py
In VSCode when the cursor is at the beginning of the line and there is a visible completion, the completion gets accepted only when the cursor is literally near the completion.  
So, for example, when the cursor is at the beginning of the line and the completion is a few tabs/stop away then accepting a completion(e.g. pressing the tab) won't accept the completion and instead trigger the tab key.
https://user-images.githubusercontent.com/471335/193867633-2130301a-4591-466a-8e80-8e350f3321e4.mov
This PR emulates this logic by adding a query context that is used by default.  
It is important to either keep this logic default or remove the default keymap for the tab at all because otherwise there will be no way to override the tab key in the user keymaps. …
=> fix: align accept completion logic with VSCode

plugin/listeners.py
`!=` part is required to ensure the value is boolean
=> fix: fix copilot.is_on_completion event context

plugin/plugin.py, requirements.txt
It has been more than a month since last `lsp_utils` release so I guess it's safe to remove deprecated `minimum_node_version` (it has been replaced by `required_node_version`).
=> refactor: remove deprecated method

language-server/package-lock.json, language-server/package.json
This reverts commit 2ad4d660b2679fad69c1d5b57e4d7d38274cdbf0.
As a temporary workaround for https://github.com/TerminalFi/LSP-copilot/issues/77 and we can then investigate what further change should be taken when we are available. 
p.s. v1.8.0 works fine but v1.8.1 is broken.
Emergency tag @timfjord @TerminalFi for approval.
=> revert: "chore: bump server to 1.8.1 (#76)"

language-server/package-lock.json, language-server/package.json, plugin/ui/completion.py, plugin/utils.py
Copilot now requests that the `doc` parameter now contains `version` with the document version. This must match what is on the server side as well. 
For now, using value of 0 seems to work, however the best scenario would be to try and get the `version` from LSP as it tracks it for us
=> fix: Invalid params: /doc must have required property 'version'

plugin/ui/panel_completion.py, plugin/utils.py
Previously we had to create an mdpopup hack which allowed the panel_completions to update a transient sheet. Core mdpopups now contains this fix and this code is no longer required
=> Removing mdpopup hack code

.editorconfig, LSP-copilot.sublime-settings, plugin/plugin.py, plugin/types.py, pyproject.toml, sublime-package.json
Resolves https://github.com/TerminalFi/LSP-copilot/issues/94
Add a `proxy` setting to `settings` in `LSP-copilot.sublime-settings`.
```js
{
"settings": {
"proxy": "username:password@host:port" // or just "host:port"
}
}
```
=> feat: add HTTP proxy support

plugin/ui/panel_completion.py
Hi there!
I've been trying to use the completions panel with key bindings only, but right now it's not possible because the panel steals focus from the view. This prevents any further view commands and forces you to close the panel using the mouse.
This PR just gives focus back to the view after opening the panel :)
=> fix: completions panel steals focus

README.md
Copilot.vim changes its directory structure so the link is dead now. I think it's fine to just the the repository URL.
=> docs: update URL of Copilot.vim

language-server/package-lock.json, language-server/package.json, plugin/constants.py, plugin/plugin.py, plugin/types.py, plugin/utils.py
This PR doesn't work by simply updating the server. I got
```
:: [05:53:05.974] <-  LSP-copilot LogMessage: {'message': '[DEBUG] [getCompletions] [2023-08-19T21:53:05.968Z] Producing empty completions due to document version mismatch. Completions requested for document version 0 but document version was 34.', 'level': 0, 'extra': ['Producing empty completions due to document version mismatch. Completions requested for document version 0 but document version was 34.'], 'metadataStr': '[DEBUG] [getCompletions] [2023-08-19T21:53:05.968Z]'}
:: [05:53:05.974] <<< LSP-copilot (49) (duration: 8ms): {'cancellationReason': 'DocumentVersionMismatch', 'completions': []}
```
in LSP's log panel.
---
Also, there is a new notification type.
```
:: [05:55:55.381] <?  LSP-copilot featureFlagsNotification: …
```
=> chore: bump server to 1.10.0

README.md
Thanks for LSP-copilot! To understand the settings I searched and came across [this issue](https://github.com/TerminalFi/LSP-copilot/issues/110) which was helpful. I think including this on the repo README.md makes sense.
Added section/table to README.md describing the Type/Default/Description for the available Settings as described in the sublime-package.json. Hopefully others will find this helpful.
=> Added Settings section to README.md

language-server/package-lock.json, language-server/package.json, plugin/plugin.py
Hmm... somehow `node bin/copilot-node-server --stdio` doesn't work while `node copilot/dist/agent.js --stdio` works. Temporarily switch to `copilot/dist/agent.js`.
=> chore: bump server to 1.24.0

Main.sublime-menu
Resolves https://github.com/TerminalFi/LSP-copilot/issues/134#issuecomment-1984397250
---
Change LSP-copilot's main menu into
And pressing the `Key Bindings` opens
=> feat: add keybindings edit in main menu

Default.sublime-keymap, LSP-copilot.sublime-settings, README.md, plugin/listeners.py, sublime-package.json
If it's `false`, the user has to add a keybinding for committing completion by himself/herself.
Resolves https://github.com/TerminalFi/LSP-copilot/issues/138
Resolves https://github.com/TerminalFi/LSP-copilot/issues/73
=> feat: add setting: commit_completion_on_tab

Main.sublime-commands, plugin/commands.py, plugin/templates/chat_panel.md.jinja, plugin/types.py, plugin/ui/chat.py
Copilot Chat natively supports Templates for questions
```
/fix
/doc
/tests
/explain
/simplify
/feedback
/help
```
This just makes them easier to use by adding Command entries and also auto injecting the current selection if not specified
=> Misc fixes and adding commands to allow users to discover more features

LSP-copilot.sublime-settings, plugin/client.py, plugin/commands.py, plugin/helpers.py, plugin/types.py, plugin/utils.py, requirements-dev.txt, sublime-package.json
Copilot uses GPT in the background. Essentially meaning you can create prompts in the chat panel. This just allows users to add re-usable prompts that can be triggered by the same logic as the build in prompts
=> feat: allow user customizable prompts for reusable logic

plugin/helpers.py, plugin/types.py
because no code is provided to Copilot.
Fixes https://github.com/TerminalFi/LSP-copilot/issues/196
---
This PR will append code to the chat template if the chat msg starts with `/`.
=> fix: `/explain` (and others) doesn't work
