- Default.sublime-keymap
- commands.py
- listeners.py
- ui.py
Proposed changes in https://github.com/TheSecEng/LSP-copilot/pull/4#discussion_r922450298
> refactor: simplify completion context key 

- ui.py
As per discussion in https://github.com/TheSecEng/LSP-copilot/pull/3#issuecomment-1187471328
> refactor: always display full text till we get a better thought

- plugin/ui/completion.py
This could potentially fix https://github.com/TheSecEng/LSP-copilot/issues/25
> fix: wrong `is_visible` status for completion

- plugin/constants.py
- plugin/plugin.py
Resolves https://github.com/TheSecEng/LSP-copilot/issues/36 if we want this.
> refactor: get plugin version from package metadata file

- plugin/commands.py
- plugin/types.py
> fix: LocalChecksOnly: update to correct parameter, update additional return status

- README.md
https://github.com/sublimelsp/repository/pull/65 has been merged.
> docs: LSP-copilot is on Package Control

- plugin/listeners.py
- plugin/ui/completion.py
No behavior change. Just make codes cleaner imho.
> tentative refactoring for #27

- .editorconfig
- .gitattributes
- .github/workflows/python.yml
- Makefile
- requirements.txt
having some issues with `mypy`. so `mypy` is postponed.
> chore: add coding style checks

- plugin/commands.py
LSP 4070-1.17.0 has been released.
https://github.com/sublimelsp/LSP/releases/tag/4070-1.17.0
> refactor: remove polyfill for LspWindowCommand

- .editorconfig
- .gitattributes
- .gitmodules
- Makefile
- Makefile.check
- plugin/commands.py
- plugin/listeners.py
- pyproject.toml
Using submodule is probably easier than maintaining stubs?
> chore: use mypy for CI

- language-server/package-lock.json
- language-server/package.json
> chore: bump server to 1.6.1

- Default.sublime-keymap
- plugin/commands.py
- plugin/ui/panel_completion.py
closes https://github.com/TerminalFi/LSP-copilot/issues/88
> chore: add a panel completions keybinding example

- README.md
Addresses https://github.com/TerminalFi/LSP-copilot/issues/23#issuecomment-1452137075
> docs: open any file before executing "sign in"

- plugin/listeners.py
- plugin/ui/completion.py
- plugin/utils.py
> fix: popup doesn't work properly for cloned views

- language-server/package-lock.json
- language-server/package.json
https://github.com/github/copilot.vim/commit/1358e8e45ecedc53daf971924a0541ddf6224faf
> chore: bump server to 1.8.4

- language-server/package-lock.json
- language-server/package.json
- plugin/plugin.py
Tested working on my Win11 PC.
> chore: bump server to 1.9.2

- Makefile
- Makefile.check
- plugin/ui/completion.py
- plugin/ui/panel_completion.py
- pyproject.toml
Imho, the latest `--preview` feature in black formatter gives better formatting results.
> chore: use "--preview" for black formatter

- .editorconfig
- plugin/client.py
- plugin/template.py
- plugin/templates/completion@popup.md.jinja
- plugin/templates/panel_completion.md.jinja
- plugin/ui/completion.py
- plugin/ui/panel_completion.py
> refactor: use Jinja2 for completion popup / panel completion

- LSP-copilot.sublime-settings
- plugin/client.py
- plugin/utils.py
https://github.com/TerminalFi/LSP-copilot/assets/32599364/e3e4c003-ec0c-40ae-b19b-32c7e90de4bd
> feat: activity indicator

- plugin/helpers.py
- plugin/template.py
- plugin/templates/chat_panel.md.jinja
- plugin/templates/completion@popup.md.jinja
- plugin/templates/panel_completion.md.jinja
- plugin/ui/chat.py
- plugin/utils.py
lol... we don't need to encode base64 thing at all. We can just use `res://Cache/LSP-copilot/avatar.png` and `res://Packages/LSP-copilot/plugin/assets/close.png` in minihtml image `src` attribute.
> refactor: replace data URL with ST's "res://..."

- plugin/commands.py
- plugin/ui/chat.py
fixes the following
- https://github.com/TerminalFi/LSP-copilot/issues/181
- https://github.com/TerminalFi/LSP-copilot/issues/182
- https://github.com/TerminalFi/LSP-copilot/issues/187
> fix: chat issues
